max_width = 100
array_width = 100
attr_fn_like_width = 100
comment_width = 100
single_line_if_else_max_width = 100

format_code_in_doc_comments = true
fn_single_line = true
format_macro_matchers = true
format_strings = false
merge_derives = false
overflow_delimited_expr = true
reorder_modules = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
where_single_line = true
unstable_features = true

license_template_path = "license_header"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
