[package]
name = "bpro"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoraprime.ch>"]
description = "Rust bitcoin wallet library for professional use"
repository = "https://github.com/pandora-prime/bpro"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "wallet"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "contrib"]

[dependencies]
amplify = "3.12.1"
lnpbp = "~0.8.0"
strict_encoding = { version = "~0.8.0", features = ["crypto", "chrono", "bitcoin"] }
commit_verify = "~0.8.0"
bp-core = { version = "~0.8.0-beta.2", features = ["wallet"] }
rgb-std = "0.8.0-rc.1"
descriptor-wallet = { version = "~0.8.2", features = ["descriptors", "miniscript", "keygen", "hwi"] }
bitcoin = "0.28.1"
miniscript = "7.0.0"
electrum-client = { version = "0.10.1", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", features = ["hex"], optional = true }
serde_yaml = { version = "0.8", optional = true }
serde_json = { version = "1", optional = true }
chrono = "0.4.19"
clap = { version = "~3.1.18", optional = true, features = ["derive"] }

[features]
default = ["serde", "cli"]
all = ["serde", "cli"]
cli = ["clap", "serde_yaml", "serde_json", "descriptor-wallet/electrum", "electrum-client"]
serde = ["serde_crate", "serde_with", "lnpbp/serde",
    "amplify/serde", "commit_verify/serde", "strict_encoding/serde",
    "descriptor-wallet/serde", "bp-core/serde", "rgb-std/serde",
    "bitcoin/use-serde"]
