[package]
name = "bpro"
version = "0.2.0"
license = "AGPL-3.0"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoraprime.ch>"]
description = "Rust bitcoin wallet library for professional use"
repository = "https://github.com/pandora-prime/bpro"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "wallet"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "contrib"]

[dependencies]
amplify = "3.13.0"
lnpbp = "~0.9.0"
strict_encoding = { version = "~0.9.0", features = ["crypto", "chrono", "bitcoin"] }
commit_verify = "~0.9.0"
bp-core = { version = "~0.9.0", features = ["wallet"] }
bitcoin_scripts = "0.9.0"
descriptor-wallet = { version = "~0.9.0", features = ["descriptors", "miniscript", "keygen", "hwi", "sign"] }
bitcoin = "0.29.2"
miniscript = "9.0.1"
hwi = "0.6.0"
electrum-client = { version = "0.12.1", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.14", features = ["hex"], optional = true }
serde_yaml = { version = "0.9", optional = true }
serde_json = { version = "1", optional = true }
chrono = "0.4.19"
clap = { version = "~3.2.23", optional = true, features = ["derive"] }

[features]
default = ["serde", "cli"]
all = ["serde", "cli", "electrum"]
electrum = ["electrum-client"]
cli = ["clap", "serde_yaml", "serde_json", "descriptor-wallet/electrum", "electrum"]
serde = ["serde_crate", "serde_with", "lnpbp/serde", "chrono/serde",
    "amplify/serde", "commit_verify/serde", "strict_encoding/serde",
    "descriptor-wallet/serde", "bp-core/serde", "bitcoin/serde"]
