codecov:
  require_ci_to_pass: no

coverage:
  precision: 1
  round: nearest
  range: "0...95"
  # TODO #30: Update codecov default requirements after release
  status:
    project:
      default:
        target: 0%
        threshold: 1%
    patch:
      default:
        target: 0%
        threshold: 1%